project_id        = "your-gcp-project-id"
credentials_file  = "/path/to/your/credentials.json"
docker_image_tag  = "gcr.io/your-gcp-project-id/hello-world-repo:${docker_image_tag}"
twilio_auth_token = "your-twilio-auth-token"
TRUSTED_IP_RANGE = "0.0.0.0/0"
